meta_product_name: "Awareness VR"
meta_title: "Using immersive technologies to expand our sense of self."
meta_description: "Meditative, out-of-body virtual reality experiences, prompting exploration into the relationship between our mind and reality."
meta_image: "no head.jpg" # should exist in `app/assets/images/`
