meta_product_name: "Awareness VR"
meta_title: "Awareness VR | Expanding our sense of self through immersive technology"
meta_description: "Meditative, out-of-body virtual reality experiences, prompting exploration into the relationship between our mind and reality."
meta_image: "http://www.awarenessvr.org/assets/no%20head-3c15f651872a37b44a1889fe5107f4e4515d834596a95c0f31fc2e92571a7a1b.jpg" # should exist in `app/assets/images/`
